[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[language.config.inlayHints]
closingBraceHints = { enable = false }
parameterHints = { enable = false }
typeHints = { enable = false }

[[language]]
name = "python"
language-server = { command = "ruff-lsp" }
formatter = { command = "black", args = [
    "--quiet",
    "--line-length",
    "120",
    "-",
] }
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "svelte"
auto-format = true

[[language]]
name = "css"
auto-format = true

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
roots = ["package.json", "astro.config.mjs"]
language-server = { command = "astro-ls", args = ["--stdio"] }
auto-format = true
# Next line to put inside the project workspace inside a .helix/languages.toml file
# config = { "typescript" = { serverPath = "/home/user/workspace/node_modules/typescript/lib/tsserverlibrary.js" }, "environment" = "node" }
