# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@nomicfoundation/slang-0.14.0" = {
      name = "_at_nomicfoundation_slash_slang";
      packageName = "@nomicfoundation/slang";
      version = "0.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang/-/slang-0.14.0.tgz";
        sha512 = "2VZCn/+SaAqlzRSVLuAf2j35BVIeSHbN1DQ9E1kwQSrXtVJTVzMogywLBvQE8hKKGTZIQV+Td9UV1qwxJYODVw==";
      };
    };
    "@nomicfoundation/solidity-analyzer-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer";
      packageName = "@nomicfoundation/solidity-analyzer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer/-/solidity-analyzer-0.1.1.tgz";
        sha512 = "1LMtXj1puAxyFusBgUIy5pZk3073cNXYnXUpuNKFghHbIit/xZgbk0AokpUADbNm3gyD6bFWl3LRFh3dhVdREg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-darwin-arm64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-darwin-arm64";
      packageName = "@nomicfoundation/solidity-analyzer-darwin-arm64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-darwin-arm64/-/solidity-analyzer-darwin-arm64-0.1.1.tgz";
        sha512 = "KcTodaQw8ivDZyF+D76FokN/HdpgGpfjc/gFCImdLUyqB6eSWVaZPazMbeAjmfhx3R0zm/NYVzxwAokFKgrc0w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-darwin-x64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-darwin-x64";
      packageName = "@nomicfoundation/solidity-analyzer-darwin-x64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-darwin-x64/-/solidity-analyzer-darwin-x64-0.1.1.tgz";
        sha512 = "XhQG4BaJE6cIbjAVtzGOGbK3sn1BO9W29uhk9J8y8fZF1DYz0Doj8QDMfpMu+A6TjPDs61lbsmeYodIDnfveSA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-freebsd-x64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-freebsd-x64";
      packageName = "@nomicfoundation/solidity-analyzer-freebsd-x64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-freebsd-x64/-/solidity-analyzer-freebsd-x64-0.1.1.tgz";
        sha512 = "GHF1VKRdHW3G8CndkwdaeLkVBi5A9u2jwtlS7SLhBc8b5U/GcoL39Q+1CSO3hYqePNP+eV5YI7Zgm0ea6kMHoA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-arm64-gnu-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-arm64-gnu";
      packageName = "@nomicfoundation/solidity-analyzer-linux-arm64-gnu";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-arm64-gnu/-/solidity-analyzer-linux-arm64-gnu-0.1.1.tgz";
        sha512 = "g4Cv2fO37ZsUENQ2vwPnZc2zRenHyAxHcyBjKcjaSmmkKrFr64yvzeNO8S3GBFCo90rfochLs99wFVGT/0owpg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-arm64-musl-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-arm64-musl";
      packageName = "@nomicfoundation/solidity-analyzer-linux-arm64-musl";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-arm64-musl/-/solidity-analyzer-linux-arm64-musl-0.1.1.tgz";
        sha512 = "WJ3CE5Oek25OGE3WwzK7oaopY8xMw9Lhb0mlYuJl/maZVo+WtP36XoQTb7bW/i8aAdHW5Z+BqrHMux23pvxG3w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-x64-gnu-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-x64-gnu";
      packageName = "@nomicfoundation/solidity-analyzer-linux-x64-gnu";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-x64-gnu/-/solidity-analyzer-linux-x64-gnu-0.1.1.tgz";
        sha512 = "5WN7leSr5fkUBBjE4f3wKENUy9HQStu7HmWqbtknfXkkil+eNWiBV275IOlpXku7v3uLsXTOKpnnGHJYI2qsdA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-x64-musl-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-x64-musl";
      packageName = "@nomicfoundation/solidity-analyzer-linux-x64-musl";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-x64-musl/-/solidity-analyzer-linux-x64-musl-0.1.1.tgz";
        sha512 = "KdYMkJOq0SYPQMmErv/63CwGwMm5XHenEna9X9aB8mQmhDBrYrlAOSsIPgFCUSL0hjxE3xHP65/EPXR/InD2+w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-arm64-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-arm64-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-arm64-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-arm64-msvc/-/solidity-analyzer-win32-arm64-msvc-0.1.1.tgz";
        sha512 = "VFZASBfl4qiBYwW5xeY20exWhmv6ww9sWu/krWSesv3q5hA0o1JuzmPHR4LPN6SUZj5vcqci0O6JOL8BPw+APg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-ia32-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-ia32-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-ia32-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-ia32-msvc/-/solidity-analyzer-win32-ia32-msvc-0.1.1.tgz";
        sha512 = "JnFkYuyCSA70j6Si6cS1A9Gh1aHTEb8kOTBApp/c7NRTFGNMH8eaInKlyuuiIbvYFhlXW4LicqyYuWNNq9hkpQ==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-x64-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-x64-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-x64-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-x64-msvc/-/solidity-analyzer-win32-x64-msvc-0.1.1.tgz";
        sha512 = "HrVJr6+WjIXGnw3Q9u6KQcbZCtk0caVWhCdFADySvRyUxJ8PnzlaP+MhwNE8oyT8OZ6ejHBRrrgjSqDCFXGirw==";
      };
    };
    "@nomicfoundation/slang-linux-x64-gnu-0.14.2" = {
      name = "_at_nomicfoundation_slash_slang-linux-x64-gnu";
      packageName = "@nomicfoundation/slang-linux-x64-gnu";
      version = "0.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-linux-x64-gnu/-/slang-linux-x64-gnu-0.14.2.tgz";
        sha256 = "sha256-92JYoB9hL0BCZ4nKOcYdLE+a2wvxzt2kh2i6DRhfxKw=";
      };
    };
  };
in
{
  "@nomicfoundation/solidity-language-server" = nodeEnv.buildNodePackage {
    name = "_at_nomicfoundation_slash_solidity-language-server";
    packageName = "@nomicfoundation/solidity-language-server";
    version = "0.8.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@nomicfoundation/solidity-language-server/-/solidity-language-server-0.8.2.tgz";
      sha512 = "shBWZB47FzbHQEGzxJKMc34/hOZ86XW39bT5WUc4F3cjSFk7UGaPOKNLVK0trPSs9ZNi9csczwFgsye0fNt4AQ==";
    };
    dependencies = [
      sources."@nomicfoundation/slang-0.14.0"
      sources."@nomicfoundation/solidity-analyzer-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-darwin-arm64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-darwin-x64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-freebsd-x64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-arm64-gnu-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-arm64-musl-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-x64-gnu-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-x64-musl-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-arm64-msvc-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-ia32-msvc-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-x64-msvc-0.1.1"
      sources."@nomicfoundation/slang-linux-x64-gnu-0.14.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Solidity language server by Nomic Foundation";
      homepage = "https://github.com/NomicFoundation/hardhat-vscode#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
