# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@nomicfoundation/slang-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang";
      packageName = "@nomicfoundation/slang";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang/-/slang-0.15.1.tgz";
        sha512 = "th7nxRWRXf583uHpWUCd8U7BYxIqJX2f3oZLff/mlPkqIr45pD2hLT/o00eCjrBIR8N7vybUULZg1CeThGNk7g==";
      };
    };
    "@nomicfoundation/slang-darwin-arm64-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-darwin-arm64";
      packageName = "@nomicfoundation/slang-darwin-arm64";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-darwin-arm64/-/slang-darwin-arm64-0.15.1.tgz";
        sha512 = "taPHlCUNNztQZJze9OlZFK9cZH8Ut4Ih4QJQo5CKebXx9vWOUtmSBfKv/M2P8hiV/iL7Q5sPwR7HY9uZYnb49Q==";
      };
    };
    "@nomicfoundation/slang-darwin-x64-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-darwin-x64";
      packageName = "@nomicfoundation/slang-darwin-x64";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-darwin-x64/-/slang-darwin-x64-0.15.1.tgz";
        sha512 = "kgZh5KQe/UcbFqn1EpyrvBuT8E6I1kWSgGPtO25t90zAqFv23sMUPdn7wLpMjngkD+quIIgrzQGUtupS5YYEig==";
      };
    };
    "@nomicfoundation/slang-linux-arm64-gnu-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-linux-arm64-gnu";
      packageName = "@nomicfoundation/slang-linux-arm64-gnu";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-linux-arm64-gnu/-/slang-linux-arm64-gnu-0.15.1.tgz";
        sha512 = "Iw8mepaccKRWllPU9l+hoe88LN9fScC0Px3nFeNQy26qk1ueO0tjovP1dhTvmGwHUxacOYPqhQTUn7Iu0oxNoQ==";
      };
    };
    "@nomicfoundation/slang-linux-arm64-musl-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-linux-arm64-musl";
      packageName = "@nomicfoundation/slang-linux-arm64-musl";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-linux-arm64-musl/-/slang-linux-arm64-musl-0.15.1.tgz";
        sha512 = "zcesdQZwRgrT7ND+3TZUjRK/uGF20EfhEfCg8ZMhrb4Q7XaK1JvtHazIs03TV8Jcs30TPkEXks8Qi0Zdfy4RuA==";
      };
    };
    "@nomicfoundation/slang-linux-x64-gnu-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-linux-x64-gnu";
      packageName = "@nomicfoundation/slang-linux-x64-gnu";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-linux-x64-gnu/-/slang-linux-x64-gnu-0.15.1.tgz";
        sha512 = "FSmAnzKm58TFIwx4r/wOZtqfDx0nI6AfvnOh8kLDF5OxpWW3r0q9fq8lyaUReg9C/ZgCZRBn+m5WGrNKCZcvPQ==";
      };
    };
    "@nomicfoundation/slang-linux-x64-musl-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-linux-x64-musl";
      packageName = "@nomicfoundation/slang-linux-x64-musl";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-linux-x64-musl/-/slang-linux-x64-musl-0.15.1.tgz";
        sha512 = "hnoA/dgeHQ8aS0SReABYkxf0d/Q6DdaKsaYv6ev21wyQA7TROxT1X3nekECLGu1GYLML8pzvD9vyAMBRKOkkyg==";
      };
    };
    "@nomicfoundation/slang-win32-arm64-msvc-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-win32-arm64-msvc";
      packageName = "@nomicfoundation/slang-win32-arm64-msvc";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-win32-arm64-msvc/-/slang-win32-arm64-msvc-0.15.1.tgz";
        sha512 = "2H0chHQ4uTh4l4UxN5fIVHR5mKaL5mfYTID6kxxxv2+KAh68EpYWwxLlkS5So90R2WcuPvFvTVKLm/uRo4h4dg==";
      };
    };
    "@nomicfoundation/slang-win32-ia32-msvc-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-win32-ia32-msvc";
      packageName = "@nomicfoundation/slang-win32-ia32-msvc";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-win32-ia32-msvc/-/slang-win32-ia32-msvc-0.15.1.tgz";
        sha512 = "CVZWBnbpFlVBg/m7bsiw70jY3p9TGH9vxq0vLEEJ56yK+QPosxPrKMcADojtGjIOjWjPSZ+lCoo5ilnW0a249g==";
      };
    };
    "@nomicfoundation/slang-win32-x64-msvc-0.15.1" = {
      name = "_at_nomicfoundation_slash_slang-win32-x64-msvc";
      packageName = "@nomicfoundation/slang-win32-x64-msvc";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang-win32-x64-msvc/-/slang-win32-x64-msvc-0.15.1.tgz";
        sha512 = "cyER8M1fdBTzIfihy55d4LGGlN/eQxDqfRUTXgJf1VvNR98tRB0Q3nBfyh5PK2yP98B4lMt3RJYDqTQu+dOVDA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer";
      packageName = "@nomicfoundation/solidity-analyzer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer/-/solidity-analyzer-0.1.1.tgz";
        sha512 = "1LMtXj1puAxyFusBgUIy5pZk3073cNXYnXUpuNKFghHbIit/xZgbk0AokpUADbNm3gyD6bFWl3LRFh3dhVdREg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-darwin-arm64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-darwin-arm64";
      packageName = "@nomicfoundation/solidity-analyzer-darwin-arm64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-darwin-arm64/-/solidity-analyzer-darwin-arm64-0.1.1.tgz";
        sha512 = "KcTodaQw8ivDZyF+D76FokN/HdpgGpfjc/gFCImdLUyqB6eSWVaZPazMbeAjmfhx3R0zm/NYVzxwAokFKgrc0w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-darwin-x64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-darwin-x64";
      packageName = "@nomicfoundation/solidity-analyzer-darwin-x64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-darwin-x64/-/solidity-analyzer-darwin-x64-0.1.1.tgz";
        sha512 = "XhQG4BaJE6cIbjAVtzGOGbK3sn1BO9W29uhk9J8y8fZF1DYz0Doj8QDMfpMu+A6TjPDs61lbsmeYodIDnfveSA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-freebsd-x64-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-freebsd-x64";
      packageName = "@nomicfoundation/solidity-analyzer-freebsd-x64";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-freebsd-x64/-/solidity-analyzer-freebsd-x64-0.1.1.tgz";
        sha512 = "GHF1VKRdHW3G8CndkwdaeLkVBi5A9u2jwtlS7SLhBc8b5U/GcoL39Q+1CSO3hYqePNP+eV5YI7Zgm0ea6kMHoA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-arm64-gnu-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-arm64-gnu";
      packageName = "@nomicfoundation/solidity-analyzer-linux-arm64-gnu";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-arm64-gnu/-/solidity-analyzer-linux-arm64-gnu-0.1.1.tgz";
        sha512 = "g4Cv2fO37ZsUENQ2vwPnZc2zRenHyAxHcyBjKcjaSmmkKrFr64yvzeNO8S3GBFCo90rfochLs99wFVGT/0owpg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-arm64-musl-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-arm64-musl";
      packageName = "@nomicfoundation/solidity-analyzer-linux-arm64-musl";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-arm64-musl/-/solidity-analyzer-linux-arm64-musl-0.1.1.tgz";
        sha512 = "WJ3CE5Oek25OGE3WwzK7oaopY8xMw9Lhb0mlYuJl/maZVo+WtP36XoQTb7bW/i8aAdHW5Z+BqrHMux23pvxG3w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-x64-gnu-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-x64-gnu";
      packageName = "@nomicfoundation/solidity-analyzer-linux-x64-gnu";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-x64-gnu/-/solidity-analyzer-linux-x64-gnu-0.1.1.tgz";
        sha512 = "5WN7leSr5fkUBBjE4f3wKENUy9HQStu7HmWqbtknfXkkil+eNWiBV275IOlpXku7v3uLsXTOKpnnGHJYI2qsdA==";
      };
    };
    "@nomicfoundation/solidity-analyzer-linux-x64-musl-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-linux-x64-musl";
      packageName = "@nomicfoundation/solidity-analyzer-linux-x64-musl";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-linux-x64-musl/-/solidity-analyzer-linux-x64-musl-0.1.1.tgz";
        sha512 = "KdYMkJOq0SYPQMmErv/63CwGwMm5XHenEna9X9aB8mQmhDBrYrlAOSsIPgFCUSL0hjxE3xHP65/EPXR/InD2+w==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-arm64-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-arm64-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-arm64-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-arm64-msvc/-/solidity-analyzer-win32-arm64-msvc-0.1.1.tgz";
        sha512 = "VFZASBfl4qiBYwW5xeY20exWhmv6ww9sWu/krWSesv3q5hA0o1JuzmPHR4LPN6SUZj5vcqci0O6JOL8BPw+APg==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-ia32-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-ia32-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-ia32-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-ia32-msvc/-/solidity-analyzer-win32-ia32-msvc-0.1.1.tgz";
        sha512 = "JnFkYuyCSA70j6Si6cS1A9Gh1aHTEb8kOTBApp/c7NRTFGNMH8eaInKlyuuiIbvYFhlXW4LicqyYuWNNq9hkpQ==";
      };
    };
    "@nomicfoundation/solidity-analyzer-win32-x64-msvc-0.1.1" = {
      name = "_at_nomicfoundation_slash_solidity-analyzer-win32-x64-msvc";
      packageName = "@nomicfoundation/solidity-analyzer-win32-x64-msvc";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/solidity-analyzer-win32-x64-msvc/-/solidity-analyzer-win32-x64-msvc-0.1.1.tgz";
        sha512 = "HrVJr6+WjIXGnw3Q9u6KQcbZCtk0caVWhCdFADySvRyUxJ8PnzlaP+MhwNE8oyT8OZ6ejHBRrrgjSqDCFXGirw==";
      };
    };
  };
in
{
  "@nomicfoundation/solidity-language-server" = nodeEnv.buildNodePackage {
    name = "_at_nomicfoundation_slash_solidity-language-server";
    packageName = "@nomicfoundation/solidity-language-server";
    version = "0.8.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@nomicfoundation/solidity-language-server/-/solidity-language-server-0.8.4.tgz";
      sha512 = "qtNsRJJWwc3hrImOqeNPlM459mJderjV04eJklGTG9AMuKNZ6w8qoWIVadXSW3bFz/b0CRJbAE0sKLC6kFNHZw==";
    };
    dependencies = [
      sources."@nomicfoundation/slang-0.15.1"
      sources."@nomicfoundation/slang-darwin-arm64-0.15.1"
      sources."@nomicfoundation/slang-darwin-x64-0.15.1"
      sources."@nomicfoundation/slang-linux-arm64-gnu-0.15.1"
      sources."@nomicfoundation/slang-linux-arm64-musl-0.15.1"
      sources."@nomicfoundation/slang-linux-x64-gnu-0.15.1"
      sources."@nomicfoundation/slang-linux-x64-musl-0.15.1"
      sources."@nomicfoundation/slang-win32-arm64-msvc-0.15.1"
      sources."@nomicfoundation/slang-win32-ia32-msvc-0.15.1"
      sources."@nomicfoundation/slang-win32-x64-msvc-0.15.1"
      sources."@nomicfoundation/solidity-analyzer-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-darwin-arm64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-darwin-x64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-freebsd-x64-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-arm64-gnu-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-arm64-musl-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-x64-gnu-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-linux-x64-musl-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-arm64-msvc-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-ia32-msvc-0.1.1"
      sources."@nomicfoundation/solidity-analyzer-win32-x64-msvc-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Solidity language server by Nomic Foundation";
      homepage = "https://github.com/NomicFoundation/hardhat-vscode#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@tailwindcss/language-server" = nodeEnv.buildNodePackage {
    name = "_at_tailwindcss_slash_language-server";
    packageName = "@tailwindcss/language-server";
    version = "0.0.21";
    src = fetchurl {
      url = "https://registry.npmjs.org/@tailwindcss/language-server/-/language-server-0.0.21.tgz";
      sha512 = "9FuVT4q/U3HRdcSPQDLekqEzt7UWRvM5lfC1kAQC6JR+AMGT0RZTGUXM74C1+3VSp9E0yS+tZFLvZ2nMZrluIA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Tailwind CSS Language Server";
      homepage = "https://github.com/tailwindlabs/tailwindcss-intellisense/tree/HEAD/packages/tailwindcss-language-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
